### ISSUE TITLE
Default route not working

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/choo#466]
### Expected behavior
Defining a route for `'/404'` should set a default route  (not found)

### Actual behavior
Default route did not work for me.

### Steps to reproduce behavior
Set these routes

```js
app.route('/', mainView)
app.route('/404', notFoundView)
app.mount('body')
```

Then visit any route different for `'/'`, it will render `mainView` anyway.

I think it might be related with [wayfarer#44](https://github.com/yoshuawuyts/wayfarer/issues/44).

**Comment by yoshuawuyts** [comment]
Oh yeah sounds like it. Oops haha

**Comment by expalmer** [comment]
What about ``app.route('/*', notFoundView)``... It works for me

**Comment by YerkoPalma** [comment]
@expalmer just tried that, and it works as a default view. IMO this is still a workaround more than a solution, but is good to know.

**Comment by YerkoPalma** [comment]
@yoshuawuyts looks like in choo@6 the wildcard route will be the only default, so I think this issue can be closed now :+1:

**Comment by yoshuawuyts** [comment]
woot!

**Comment by YerkoPalma** [comment]
I'm saying that this PR #521 _resolves_ this issue. Am I wrong?

**Comment by yoshuawuyts** [comment]
I _think_ this should be resolved, yeah - but not entirely positive because we need a test to see if `'/*'` and `'/'` resolve differently on root. PR welcome over on bankai for the test https://github.com/yoshuawuyts/wayfarer/blob/master/test/router.js
