### ISSUE TITLE
Remove nanomount

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/choo#481]
We can get a faster meaningful paint / time to live by removing `nanomount` and just replacing all of the `<body>` (we're a top level framework, think it's fine if we take control of what goes on in `<body>`). This would be a breaking change tho, and personally I'd want to wait for an update in `bankai` first to make the `<script>` tag async.

### See Also
- https://github.com/yoshuawuyts/bankai/issues/166
- https://github.com/sethvincent/create-html/issues/4
- http://caniuse.com/#feat=script-async
- https://developer.mozilla.org/en/HTML/Element/script#Attributes

**Comment by bcomnes** [comment]
React cautions against taking over body because sometimes browser addons mount there. ` ¯\_(ツ)_/¯`

**Comment by tgfjt** [comment]
mmm,
IMO, removing `nanomount` is ok, but mounting only `body` is not ok for me.

**Comment by yoshuawuyts** [comment]
@bcomnes Hah, yeah with you - I'm not too worried about that one. Afaik none of the extensions I use currently conflict with this, and I reckon most people (e.g. not power users) might not even be running any extensions at all. If an extension really wants to stick on the DOM, they can always re-mount if ever unmounted.

---

@tgfjt oh yeah, wasn't implying we only allow mounting on `body` - Nanomount mostly exists so that in the current context we can mount on `body` safely

**Comment by toddself** [comment]
Are there going to be hoops to jump through to not-mount-on-body or other perf issues?

Namely we use things like intercom that want to be loaded via a script tag provided at the end of the body (so they don't have to deal with DOMContentLoaded or document ready stuff).  I'd prefer to not have the choo app append this stuff for me since if I have it inlined in the returned document it can start fetching data and appear to the user quicker than if choo were to add it during the render loop.

This is also a much easier way for us to attach bootstrap data from the request, since we can append a script tag to the end of the body tag (since body and html are implied close tags we just don't provide them on our HTML fixture).

**Comment by yoshuawuyts** [comment]
oh yeah, so I removed the script tag copying from choo 6 b/c you can
achieve the same result with an `async` attribute on a script tag in head.
Sounds like the intercom thing is rather aggressive; I wouldn't be
surprised if it has a non-negligable effect on boot performance. Not that
choo cares tho; `app.mount()` is possible on any node - but I think
generally speaking it's still preferable to mount on `body` so that the
entire page is rendered deterministically, and not just a part of it. Does
that make sense?

**Comment by toddself** [comment]
Its not only including the script: we have to provide a custom config to it after it loads. I guess we can move all this into a component...  

The other thing though I can think of is google's web auth (and intercom) are appending iframes to the body to provide their functionality. Is this going to remove them? Google and intercom aren't going to reinject them except on a full page reload, so if pushState is going to replace the entire body, thats going to make those tools unreliable.

**Comment by yoshuawuyts** [comment]
If your application code relies on third party code to inject things on
body, then mounting on body might indeed not be a good idea. But like you
say: generally having a component makes a lot of sense (e.g. multi-regl was
recently componentized https://github.com/substack/regl-component, resulted
in code that's easier to reason about too :D). But like I said: out of the
box choo holds no opinions on which element it's mounted, so don't worry
about mounting it on some element under body C:

**Comment by toddself** [comment]
OK cool.  Just wanted to make sure non-body elements were going to get the short end of the perf stick.  But the top-level tag in each "view" does need to be of the same type?

Our application code doesn't inject -- services we rely on do.  Intercom is the obnoxious "chat window" that gets added to a page.  We use it for getting instant help for our users.

**Comment by goto-bus-stop** [comment]
suppose this was done in https://github.com/choojs/choo/pull/489
