### ISSUE TITLE
Choo v5 / v6 onload handlers on root node not called when navigating

### ISSUE THREAD

**Issue by mantoni** [choojs/choo#490]
### Steps to reproduce behavior

Create two pages:

- `/foo` with root `<div>`
- `/bar` with root `<div onload=${myHandler}>`

### Expected behavior

Navigating from `/foo` to `/bar` triggers the `onload` handler

### Actual behavior

The `onload` handler is not triggered upon navigation. It is triggered when loading the `/bar` page initially though.

### Workaround

Attaching the `onload` handler to a child node fixes the issue.

The workaround is simple enough to apply. If this is tricky to solve, I think an assertion would also do.

**Comment by bengourley** [comment]
If I understand it correctly, this is a typical [nanomorph](https://github.com/yoshuawuyts/nanomorph)/[morphdom](https://github.com/patrick-steele-idem/morphdom) issue… when you navigate between routes, the diffing algorithm compares…

before: `<div></div>`
after: `<div onload=${fn}></div>`

It sees that the element that exists is already a `<div>` so doesn't need to replace it, just add an attribute. Since the semantics of `onload` are "when the element is added to the DOM" and this element is _already_ in the DOM, it correctly (but confusingly) doesn't fire.

I don't know what the best approach for your problem is this but I hope this helps explain why it doesn't work!

**Comment by mantoni** [comment]
@bengourley Thanks for elaborating. I'm aware of this behavior, but still crashed into this and got confused. It should somehow be handled or highlighted by Choo, I think.

**Comment by josephluck** [comment]
If you set unique IDs on the nodes, it'll treat it as a new node and onload will fire correctly On 9 May 2017 09:57, Maximilian Antoni <notifications@github.com> wrote:@bengourley Thanks for elaborating. I'm aware of this behavior, but still crashed into this and got confused. It should somehow be handled or highlighted by Choo, I think.

**Comment by mantoni** [comment]
No, setting unique IDs on the nodes does not help. Actually, the `onload` handler generates dynamic data properties that are already unique (as long as the called handler function is different).

Here is a minimal Choo app to illustrate the issue:

```js
var html = require('choo/html')
var choo = require('choo')

var app = choo()

function onloadA() {
  console.log('onload A')
}

function onloadB() {
  console.log('onload B')
}

app.route('/a', function (state, emit) {
  return html`<div onload=${onloadA} id="a"><a href="/b">Go to A</a></div>`
})
app.route('/b', function (state, emit) {
  return html`<div onload=${onloadB} id="b"><a href="/a">Go to B</a></div>`
})

document.body.appendChild(app.start())
```

Save as `issue.js`, run with `budo issue.js --pushstate` and open <http://localhost:9966/a>.

**Comment by mantoni** [comment]
Actually, if you look at the DOM changes when navigating between `/a` and `/b`, you can observe that the `id` property is changed on the root node while the `data-onloadHASH` property is not. Only `onload A` makes it to the console on first load.

**Comment by nilliams** [comment]
I just hit this too and can confirm the issue. Looking at the nanomorph code I spotted another workaround that seems to work, setting unique values for `data-onloadid` on your root elements, which is slightly nicer than setting it on a child element (as that can require creating one just for the purpose).

**Comment by yoshuawuyts** [comment]
Think this is related - we need to change this (:
https://github.com/yoshuawuyts/nanomorph/issues/63

**Comment by yoshuawuyts** [comment]
https://github.com/yoshuawuyts/nanomorph/issues/63 will land in choo v6 :sparkles:

**Comment by mantoni** [comment]
I had another look with Choo 6.0 and Choo 6.5. Now none of the `onload` handlers is fired anymore with the example posted above. Previously, at least the initial `onload` handler was fired. Is this intentional and root node `onload` is not supported at all anymore?

**Comment by yoshuawuyts** [comment]
@mantoni yeah, we removed it entirely — this was a breaking change in `v6.0.0`, but needed to happen because using `onload` with DOM diffing doesn't work. We recommend using [nanocomponent](https://github.com/choojs/nanocomponent) instead!

Does that make sense?

**Comment by mantoni** [comment]
Makes sense. It's at least consistent now. However, I'd personally think this is a common thing to try when playing with Choo. How about adding an assertion?

**Comment by yoshuawuyts** [comment]
What do you mean by assertion? Where would it go?

**Comment by mantoni** [comment]
I‘m mean that Choo should throw if you’re using `onload` on a root element. Because it’s working otherwise, just not on the root.

**Comment by yoshuawuyts** [comment]
@mantoni please check you're running the latest bel; I made sure to remove it in a major version a couple of months ago. There's valid use cases for an `onload` attribute that acts differently from the `on-load` package, so throwing when it's used would probably be a conflicting (breaking even) change. Does this make sense?

**Comment by mantoni** [comment]
@yoshuawuyts Thanks for the pointer. Took me a while to find out why my code is still working 😅

Turns out I'm always going through `yo-yoify` and never hit `bel` directly. The `onload` feature was not removed from `yo-yoify` (yet).

Closing issue since it's by design. However, I'm not sure how I'm supposed to migrate my codebase once `onload` stops working. I depend heavily on this feature and using the `on-load` library is not as convenient 🤔

**Comment by yoshuawuyts** [comment]
Short reply as it's late, but check out:
- https://github.com/choojs/nanocomponent
- https://github.com/choojs/choo/issues/593
