### ISSUE TITLE
Modifying state to a new object in a plugin doesn't update current state

### ISSUE THREAD

**Issue by thekemkid** [choojs/choo#535]
### Expected behavior
I am doing server rendering, and I'm looking to embed the server state in window.initialState object when sending the html body. To enable choo to pick it up, I have a super simple plugin like so:

```js
app.use(serverState)
function serverState (state, emitter) {
    state = window.initialState || state
}
```

### Actual behavior
I expected state to be the window.initialState object later - but that doesn't happen. Obviously because I just referenced another object, and didn't extend the existing one. Silly javascript, and silly me for thinking it works :)

Would it be possible to allow you to return the new state from a plugin? so state that gets passed is immutable, and whats returned is set to the new state? This would be a breaking change obviously, so not to be taken lightly 🤔

I would suggest the following for the new `choo.use`

```js
Choo.prototype.use = function (cb) {
  assert.equal(typeof cb, 'function', 'choo.use: cb should be type function')
  var endTiming = nanotiming('choo.use')
  this.state = cb(object.assign({}, this.state), this.emitter, this)
  endTiming()
}
```

This would make us write plugins like so:

```js
function myPlugin (state, emitter, choo) {
  const nextState = window.initialState || state
  return nextState
}
```

which then means you can't make the same silly mistake I made.

ps: I resolved the issue I was having by adding changing my serverState code to
```js
function serverState (state, emitter) {
    Object.keys(window.initialState).forEach((k) => { state[k] = window.initialState[k]; })
}
```

**Comment by yoshuawuyts** [comment]
Hm, well from a _safety_ point of view, it's dangerous to modify the `state` reference entirely. Other plugins often rely on built-in values from it, and if not handled carefully it can cause seemingly random things to fail.

Copying over properties seems like the right approach in almost every case. For edge cases (such as state being a shared memory object using electron / the new shared memory API) you could pass the `app` instance to a function that makes it explicit that the `app.state` object is being modified. That way plugins are "safe" by default, but choo's internal state can still be modified.

Hope this makes sense!
