### ISSUE TITLE
Falsy attributes are rendered by pelo

### ISSUE THREAD

**Issue by tornqvist** [choojs/choo#542]
Since not actually parsing the html is what makes pelo fast compared to bel, I'm not quite sure how this could be addressed but nonetheless it's an issue that output differs. Also these kinds of patterns, using booleans to determine i.e. input disabled state is quite common, at least in my case.

### Expected behavior

Elements with interpolated falsy (`null`/`false`) values be excluded from output.

```javascript
html`<input disabled=${ false } />`
```

### Actual behavior

```html
<!-- pelo output -->
<input disabled="" />

<!-- bel output -->
<input />
```

Pelo renders attributes with falsy values as `attribute=""` whereas bel completely excludes them.

### Steps to reproduce behavior
See requirebin: http://requirebin.com/?gist=1dc8acd84ec5bb811458131431bffc4b

**Comment by bcomnes** [comment]
Thanks!  Upstreaming this to https://github.com/shuhei/pelo/issues/8

**Comment by bcomnes** [comment]
A fix is out: https://github.com/shuhei/pelo/issues/8#event-1192259430 in `pelo@0.0.3`.  Anyone feel up to bumping `bel`?

**Comment by bcomnes** [comment]
Fixed in https://github.com/shama/bel/releases/tag/v5.0.3 and no updates required for Choo to get that.  🙌

**Comment by bcomnes** [comment]
Please let me know if that doesn't fix the issue and we can reopen.
