### ISSUE TITLE
Server Rendered Example

### ISSUE THREAD

**Issue by hdriqi** [choojs/choo#543]
Hello, Can somebody create an example of choo server rendered using expressjs??

Thanks

**Comment by bcomnes** [comment]
We lost a few examples in the recent updates to Choo, but here are the old examples from Choo 4 that need to be brought forward to Choo 5/6:

- https://github.com/choojs/choo/tree/v4.1.0/examples/server-rendering
- https://github.com/jondashkyle/jon-kyle.com <- static ssr example

Its on the TODO list, but if you come up with a good example we can add it to the example section.

**Comment by hdriqi** [comment]
Here's my example for choo ssr. Any suggestions?

https://github.com/hdriqi/choo-ssr-example

**Comment by bcomnes** [comment]
I like it from the look!  I'll (or whoever beats me to it) will look at this more soon.  We should probably have an SSR example with bankai, but I think the express example is good too.

**Comment by graforlock** [comment]
There is express one here as well: 

https://github.com/graforlock/choo-bandwagon
