### ISSUE TITLE
Can't set state in use hook

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/choo#544]
### Expected behavior
When seting state like this

```js
app.use(function (state) {
  state = {
    a: 'some',
    b: 'value'
  }
})
```

then, the state should be able to access props like `state.a` and `state.b`

### Actual behavior

Above code didn't work for me. I had to do

```js
app.use(function (state) {
  state.a = 'some'
  state.b = 'value'  
})
```

### Steps to reproduce behavior

Run the above code, I haven't any repo yet, but if needed I will have one tomorrow ;)

**Comment by yoshuawuyts** [comment]
You can't reassign the state object in the scope, JS doesnt handle Objects
that way; you need to assign properties to the existing object that's
passed down in the callback.

So do `state.foo =`, or `Object.extend(state, newProps)`. Hope that makes
sense!

**Comment by YerkoPalma** [comment]
It makes sense, thanks for the answer.

**Comment by yoshuawuyts** [comment]
Yay, happy to help!

**Comment by rafaelamorim** [comment]
@yoshuawuyts ... also got some questions within the same topic:
- Is there any examples on how to use immutable states? (maybe with immutable.js?)
- Why barracks got dropped out since v5 (app.model)? Is there a way to still use it with v6?

Best :)

**Comment by bcomnes** [comment]
@rafaelamorim 

- To use immutable, I believe you can just assign immutable objects to properties of state, and then have your components use that.
- Barracks still exists https://github.com/yoshuawuyts/barracks. I would love to see an example of someone hooking it up to Choo 6.  I haven't tried it yet.
