### ISSUE TITLE
state.query not set until navigate

### ISSUE THREAD

**Issue by jondashkyle** [choojs/choo#549]
When going to a direct link with a query string, such as `/example?foo=bar`, the `state` object does not contain `query`. But, if you navigate to that URL by clicking a link, it’ll appear as expected.

That seems to be a bug, but just checking the intent before filing a PR. One other question; should `query` always be in `state`, similar to `params`? Could reduce a check or two.

**Comment by yoshuawuyts** [comment]
Yeah, it should always be in there. Definitely sounds like a bug.

**Comment by mantoni** [comment]
Just ran into this as well. The `state.query` object is populated properly, but I have to delay reading from it. It's not yet populated during model initialization.

**Comment by yoshuawuyts** [comment]
Yeah, we should probably document properly that all of these values are
only initialized _after_ DOMContentLoaded

**Comment by yoshuawuyts** [comment]
Should be fixed in `choo@6.7.0` :tada:
