### ISSUE TITLE
Possibility to use choo without routing/router

### ISSUE THREAD

**Issue by graforlock** [choojs/choo#556]
### Expected behavior

When working in a hybrid, microservice routing environment, I should just mount the specific route (e.g. after code split) without using the any (or pushstate) router. Express is now a source of truth for router.

### Actual behavior

When working in a hybrid, microservice routing environment, I need to double up for express router instead letting express hit the route with `name-of-route.js` script. Express isn't now a source of truth for router.

I could not find answer to that in any documentation bit so far, hence the question. Is it possible? It is because we have a higher level routing solution routing the site to many different places, places using different technologies that only share the theme, and are microservices essentially.

**Comment by yoshuawuyts** [comment]
Heya! I tried answering this on IRC a lil bit back, but you popped out before I could finish writing my reply. Anyway, here is!

```txt
maciejsitko> hey, is there a possibility not to use router? we have code splitting in the company and all routing is done by express anyway (it just hits different budnles per route)
14:47 <maciejsitko> pushstate router kind of gets in the way this way
14:47 ⇐ maciejsitko quit (1fdd04a2@gateway/web/freenode/ip.31.221.4.162) Client Quit
14:48 <yoshuawuyts> maciejsitko: not really unfortunately; most of choo's glue is centered around the router. If your build process requires a custom routing it might be best to roll your own choo
```

**Comment by graforlock** [comment]
Yeah, I kind of lost it somewhere and didn't see the answer. It'd be a nice have as it'd be a much more flexible (like in React for that matter) and truly micro.

**Comment by brechtpm** [comment]
If you're looking for something more like React, maybe it's [yo-yo](https://github.com/maxogden/yo-yo) that you're after?

**Comment by bcomnes** [comment]
@graforlock you can also use nested nanocomponents and a top level controller class to achieve something similar.

**Comment by graforlock** [comment]
Im not really looking for something like React, I like the choo API, I just think it would be a bit more flexible without being baked in / tightly coupled with pushstate router, or any kind of router for that matter. Just mounting it to the DOM opens possibilities for people adopting `choo` gradually/progressively, for instance, and many many more that doesn't just include SPAs.

**Comment by jonjaques** [comment]
Can't you just do something like this?

```
const app = Choo({history: false})

app.route(window.location.href, mainView)
app.mount(...)

function mainView(state, emit) {
  switch(state.cond) {
    case 'a': return html``
    case ...
  }
}

```

That way it won't listen for or try to pushState on links, just a full page reload. If you want to switch views, just do so via state.

**Comment by graforlock** [comment]
Seems to work, other than in isomorphic apps there is a need to provide the feature check (like `isSSR`) for  window context.

**Comment by jonjaques** [comment]
Awesome! Updated my example by exporting the app and then check for global.document. I believe there is an internal property inside choo that already checks, but this worked for me in a commonjs (webpack) environment.

**Comment by graforlock** [comment]
Two separate bundles is the only reasonable solution at this point. Its "hackish" anyway, but works.

**Comment by graforlock** [comment]
If anyone's interested, a wrapper to allow just that:

https://github.com/graforlock/choo-detached
