### ISSUE TITLE
touch events don't work

### ISSUE THREAD

**Issue by graforlock** [choojs/choo#558]
### Expected behavior
`ontouchstart=${someFunction}` registers a function callback.

### Actual behavior
`ontouchstart=${someFunction}` doesn't register a function callback.

### Steps to reproduce behavior

Try the following in Google Chrome mobile inspector:

```javascript
html`
   <div ontouchstart=${() => console.log('log...')}> 
       Stuff here...
   </div>
`;
```

**Comment by YerkoPalma** [comment]
Did you try with [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) those should cover touch events and fallback to mouse events, also depends on the chrome version. 
Other thing to try is to attach the event in javascript with `addEventListener`, if that works it may be a bel issue

**Comment by graforlock** [comment]
I believe the issue is different. 

There are missing touch events in nanomorph:

https://github.com/choojs/nanomorph/pull/78

in Chrome mobile `ontouchstart` view is available when i try it in console - it just doesn't fire.

**Comment by graforlock** [comment]
It seems to be Chrome inspector issue, and its not to do with choo, Im closing.

**Comment by bcomnes** [comment]
Doh!  How did you figure it out?

**Comment by bcomnes** [comment]
@graforlock any idea if https://github.com/choojs/nanomorph/pull/78 is still needed?

**Comment by yoshuawuyts** [comment]
Does this work now?
