### ISSUE TITLE
bel raw html helper

### ISSUE THREAD

**Issue by graforlock** [choojs/choo#562]
### Expected behavior
I can get `choo/raw` import.

### Actual behavior
I cannot import bel's raw helper even though choo exports bel

Any thoughts on that? I would be sweet to get that without having the need of requiring/installing another `bel` package. 'raw' is quite essential for rendering anything from CMS data/APIs for instance.

Its an enhancement.

**Pull request** at [#565](https://github.com/choojs/choo/pull/565)

**Comment by YerkoPalma** [comment]
Have you tried with `choo/html/raw`?

**Comment by yoshuawuyts** [comment]
We're not exporting it yet. A patch to add it as `choo/raw` would be welcome!

cc/ @bcomnes @jondashkyle how do you feel about exporting it with the ^ API? That was always the plan, right?

**Comment by bcomnes** [comment]
makes sense!  I was going to suggest this but didn't have a chance.  TY @graforlock

**Comment by graforlock** [comment]
Well, there's a pull request atm but its namespaced in html, so it's not `choo/raw` but `choo/html/raw` as @YerkoPalma wrote: I think its clearer, less confusing of what it is. What do you think?

**Comment by yoshuawuyts** [comment]
Yeah, works for me too - I'm fine with either (:

**Comment by graforlock** [comment]
I'm closing as it got morphed.. merged.
