### ISSUE TITLE
Q: Inline onload supposed to work ?

### ISSUE THREAD

**Issue by antenando** [choojs/choo#570]
Greetings from Brazil!

First of all, my sincere congrats for this amazing fw. 

I have a simple question.

Why doesn't the inline `onload` work at the case below?

```js
import choo from 'choo'
import html from 'choo/html'
import log from 'choo-log'
import onload from 'on-load'

export const testView = (state, emit) => {

	function onloadFn(el) {
		console.log('onLoad!', el);
	}

	return html`
		<div onload=${onloadFn}>
			<h1>test!</h1>
		</div>
	`
}

const app = choo()
app.use(log())
app.route('*', testView)
app.mount('#root')
```

but this does work ?

```js
import choo from 'choo'
import html from 'choo/html'
import log from 'choo-log'
import onload from 'on-load'

export const testView = (state, emit) => {

	function onloadFn(el) {
		console.log('onLoad!', el);
	}

	const tree = html`
		<div>
			<h1>test!</h1>
		</div>
	`

	onload(tree, onloadFn)

	return tree
}

const app = choo()
app.use(log())
app.route('*', testView)
app.mount('#root')
```

What am I doing wrong?

Would love to understand it better.

Keep it up!

**Comment by goto-bus-stop** [comment]
choo@6 uses bel@5, which no longer includes the `onload` and `onunload` attributes. You have to do it like in your second snippet now.

**Comment by antenando** [comment]
Not a problem. Thanks for the background! Cheers

**Comment by antenando** [comment]
Just another quick one: is there an official central and up to date repository for the documentation?

I always find bits and pieces of code for things that doesn't work anymore with Choo.

**Comment by graforlock** [comment]
you can just do 

```javascript
const div = html`<div></div>`

div.onload = () => {}
```

as well, or as said before, with `on-load`

**Comment by goto-bus-stop** [comment]
I don't think you can do that, `bel` compiled `<div onload=${xyz} />` to `onload(el, xyz)` before v5. `div.onload = xyz` is something different.

**Comment by graforlock** [comment]
It is something different as it just does dom onload event, which is most of the times a correct interface of GlobalEventHandlers

**Comment by yoshuawuyts** [comment]
Heya, sorry that docs aren't up to date - will be focusing (full time) on
getting more out in the next few weeks; so stay tuned! :D
