### ISSUE TITLE
Render specific component

### ISSUE THREAD

**Issue by hdriqi** [choojs/choo#581]
I am using ChartistJS to generates the chart, but when I do emitter.emit('render') the Chart element is gone because its children element is basically generated on the fly.

I thought that maybe ChooJS can only re-render specific element? 
or maybe there's some workaround? For now I generate the chart all over again after each re-rendering.

**Comment by YerkoPalma** [comment]
For this case I use nanocomponent, since every component has its own lyfecicle, including renderings

**Comment by yoshuawuyts** [comment]
@hdriqi did you get a chance to try out [nanocomponent](https://github.com/choojs/nanocomponent)?

**Comment by hdriqi** [comment]
@YerkoPalma @yoshuawuyts just saw it and its really cool. Previously my workaround is override .isSameNode and always return true so. Thanks!

**Comment by yoshuawuyts** [comment]
Yay, glad to hear it worked out for you! ☺️
