### ISSUE TITLE
Server-side rendering object yields [object Object]

### ISSUE THREAD

**Issue by graforlock** [choojs/choo#591]
### Expected behavior
When I pass input like this:

```javascript
<a href="/link" ${title ? {title} : '' }>Link</a>
```

the rendered markup is 

```javascript
<a href="/link" title="My title" >Link</a>
```
on the server.

### Actual behavior
When I pass input like this:

```javascript
<a href="/link" ${title ? {title} : '' }>Link</a>
```

the rendered markup is 

```javascript
<a href="/link" [object Object] >Link</a>
```
on the server.

### Steps to reproduce behavior
Try to render it toString() on server side.

Sometimes for SEO purposes, you'd want to avoid leaving blank attributes like `<a href="/link" title>Link</a>`, hence the need to have a good way of not rendering these at all.

 Passing object is fine on the client-side, but it has different behaviour on the server.

Its mainly related to `pelo` I presume and has to be fixed there?

**Comment by YerkoPalma** [comment]
Does this rendering work in the browser?

**Comment by goto-bus-stop** [comment]
yeah pelo doesn't support rendering attributes from an object. mind opening an issue over there?

**Comment by graforlock** [comment]
Yeah, will do. Just wanted to kinda cross-reference since its core functionality.

**Comment by graforlock** [comment]
Merged but awaiting caret change and a new version published in `bel` 

Anyone there? (I know @bcomnes  approved of it)

**Comment by yoshuawuyts** [comment]
Thanks! updated `bel` to `v5.1.4` which should fix this issue. Think it should be fixed now; closing! :grin:
