### ISSUE TITLE
TypeError: html is not a function

### ISSUE THREAD

**Issue by timsim00** [choojs/choo#607]
### Expected behavior
Ability to use bel multiple times in a module.

### Actual behavior
If I try to use bel a second time in a module, I get "html is not a function."

### Steps to reproduce behavior
In a view:
const html = require('choo/html')

module.exports = function (state, emit, props = {}) {
  return html`...${otherFn()}...`
...
function otherFn() {
  return html`...`

**Comment by goto-bus-stop** [comment]
this sounds to me like the `html` import is stripped by yo-yoify, but it is still used somehow. are you using yo-yoify (whether manually or through bankai)?

could you post an actual snippet that produces the error?

**Comment by goto-bus-stop** [comment]
@timsim00 is this still an issue?

**Comment by timsim00** [comment]
I haven't seen this error in a while.  Could have been new user error.
