### ISSUE TITLE
Multiple nested views

### ISSUE THREAD

**Issue by timsim00** [choojs/choo#608]
Let's say I have an app with multiple tabs, and one tab has a wizard (multiple steps connected via next/back buttons).

Does every view always have to specify the entire page:
return html`<id=page>
${header()}
${tabs()}
<id=content>some nested view content</content>
${footer()}
</page>`

Or is there a pattern where a nested view can just returns it's own content?
return html`...nested content...`

**Comment by goto-bus-stop** [comment]
AFAICT most people have something like a `layout` function that you can pass page content to.

```js
function layout (state, content) {
  return html`
    <div id=${state.pageId}>
      ${header()} ${tabs()}
      <div id="content">${content}</div>
      ${footer()}
    </div>
  `
}

function homeView (state, emit) {
  return layout(state, html`
    <h1>Main page content</h1>
  `)
}

app.route('/home', homeView)
```

**Comment by timsim00** [comment]
That makes sense.  Thanks, I give it whirl.

**Comment by goto-bus-stop** [comment]
there is also a website PR for documentation using a similar approach: https://github.com/choojs/website/pull/43
