### ISSUE TITLE
Navigate event should enable action on "page entry"

### ISSUE THREAD

**Issue by HoverBaum** [choojs/choo#610]
### Expected behavior
Listening for the navigate event should enable programmers to do things on "page entry".

### Actual behavior
Navigate event provides no context of from where to where a user is going. `state.route` still holds the old route when the event is fired.

### Use-case

Trigger an event when a user enters a page. This is useful to display messages or fetch data from the backend but only when a user enters a page and not when it is re-rendered.

## Proposal

I could see a few things that could be a solution to this problem and for these use-cases.

1. The Navigate event updated to only trigger listeners once the navigation has happened. As proposed by @yoshuawuyts:
> "navigate triggers" -> "router triggers" -> "state.route is updated" -> "route is triggered" -> "all other listeners for navigate are triggered"
2. The Navigation event carries information about the navigation happening. We could for example add the route we are coming from and going to.

**Comment by yoshuawuyts** [comment]
Should be fixed in `choo@6.7.0` :tada:
