### ISSUE TITLE
how to use/import external css files in choo components ?

### ISSUE THREAD

**Issue by varvarasd** [choojs/choo#655]
Hi,
I've been looking around for info on how to use/import external css files in choo.js components and can't find anything clear on this topic unfortunately.
Please can someone clarify with an example ?

Many thanks!

**Comment by reinseth** [comment]
[create-choo-app](https://github.com/choojs/create-choo-app) demonstrates this using [sheetify](https://github.com/stackcss/sheetify) to import [tachyons](http://tachyons.io/).

**Comment by goto-bus-stop** [comment]
Yep, with [`sheetify`](https://npmjs.com/sheetify) you can do `css('./external/css/file.css')`. And if you want to use `@import` syntax in a css file you can use [`sheetify-postcss`](https://npmjs.com/sheetify-postcss) with the [`postcss-import`](https://npmjs.com/postcss-import) plugin. Hope that works for you!
