### ISSUE TITLE
Choo SSR w/ Express example

### ISSUE THREAD

**Issue by coetry** [choojs/choo#657]
Can someone post a quick gist demonstrating Choo on the front and Express in the back w/ SSR?

**Comment by coetry** [comment]
that's awesome! i will explore it and ping you if I have any further questions!

**Comment by graforlock** [comment]
Note that this cli/generator uses old style store rehydration, it would most likely be updated for the new API that allows you to do `initialState` like this: https://github.com/choojs/choo#server-rendering

**Comment by graforlock** [comment]
Bumped to `0.0.6` so you can now see full example with `initialState` hydration
