### ISSUE TITLE
How to ensure every route emits DOMContentLoaded?

### ISSUE THREAD

**Issue by NetOperatorWibby** [choojs/choo#664]
### Expected behavior

```js
emitter.on("DOMContentLoaded", function () {
  log("hi"); // returns "hi" in the console
});
```

### Actual behavior

```js
emitter.on("DOMContentLoaded", function () {
  log("hi"); // returns nothing in the console
});
```

### Steps to reproduce behavior
Start writing a plugin like this:

```js
// client.js
app.use(require("/path/to/my-plugin")());
```

```js
// my-plugin.js
function myPlugin () {
  return function (state, emitter) {
    emitter.on("DOMContentLoaded", () => {
      log("hi");
    });
  };
}

module.exports = exports = myPlugin;
```

**Comment by goto-bus-stop** [comment]
DOMContentLoaded is supposed to fire only once per page load, even if you navigate to other routes. There is a `navigate` event that is fired when you navigate to other routes: https://github.com/choojs/choo#navigatestateeventsnavigate

**Comment by NetOperatorWibby** [comment]
I managed to get _something_ working but in the end, hooking into Fastify worked for my purposes. I'm super delayed in saying this but, thanks for the assistance.
