### ISSUE TITLE
Use choo directly in the frontend

### ISSUE THREAD

**Issue by fredooer** [choojs/choo#671]
### Is there any way to use choo directly in the frontend without npm?

I mean something like:

```html
<script src="dist/choo.js"></script>
<script>
  // You can use choo now
  var app = choo();
  // app.something() ...
</script>
```

**Comment by YerkoPalma** [comment]
choo and nanohtml includes umd builds. I have set up a minimal example in [codepen here](https://codepen.io/YerkoPalma/pen/wXrrdb).

The key is to refer the bundle files in the dist folder `https://unpkg.com/choo/dist/bundle.js` (notice that there is also a minified bundler version there)

**Comment by fredooer** [comment]
It works!

_Thank you @YerkoPalma_
