### ISSUE TITLE
Minify rendered front-end code

### ISSUE THREAD

**Issue by NetOperatorWibby** [choojs/choo#680]
### Expected behavior
I'd like an option to minify what choo outputs.

### Actual behavior
Currently, this functionality doesn't exist.

### Steps to reproduce behavior
N/A

**Comment by bcomnes** [comment]
Try https://github.com/browserify/tinyify and doesn't bankai do this already?

**Comment by NetOperatorWibby** [comment]
I'm not using bankai. Too much magic and I like seeing things in console. I'll try tinify with rollup though, thanks for the suggestion @bcomnes.

**Comment by bcomnes** [comment]
Totally understand, a few of my projects need the transparency as well.  Closing, but we can reopen if there are other issues.

**Comment by goto-bus-stop** [comment]
Tinyify only works with Browserify, for rollup look into something like rollup-plugin-terser

**Comment by NetOperatorWibby** [comment]
Will do!
