### ISSUE TITLE
Is choo abandoned / no longer maintained?

### ISSUE THREAD

**Issue by obv-mikhail** [choojs/choo#686]

**Comment by yoshuawuyts** [comment]
It's considered stable & feature complete. Critical issues are addressed, but there's currently nobody being paid to work full time on it.

**Comment by obv-mikhail** [comment]
@yoshuawuyts Ok, thanks. The very old pull requests that are neither merged nor rejected make the project look unmaintained.

**Comment by yoshuawuyts** [comment]
@obv-mikhail ah yeah, I can imagine the optics of that aren't great. The truth to that is though that a a lot of those are good PRs that require a bit more work in the ecosystem to fully support. We haven't properly scoped out a next major version yet, and they'd be part of that so they haven't been merged yet into mainline Choo. Which means they've been open for a while, and probably will be until the next semver major.

Does that make sense?

**Comment by obv-mikhail** [comment]
@yoshuawuyts Yes it does. Thanks again.
