### ISSUE TITLE
Is it possible to use choojs with es import syntax?

### ISSUE THREAD

**Issue by bennlich** [choojs/choo#702]
ES modules have come a long way, and [MDN says](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) `import` is now supported by most browsers. I'd love to `import {choo} from 'choo.js'`. Any recommendations? Does Bankai handle this?

:smiley_cat:

**Comment by goto-bus-stop** [comment]
```js
import choo from 'choo'
```
this should work in bankai, because it includes the Babel ES → CJS transform. choo doesn't ship an es modules build yet though

**Comment by bennlich** [comment]
Thanks! I'll give this a shot.
