### ISSUE TITLE
[domain] ssl-cert expired

### ISSUE THREAD

**Issue by dym-sh** [choojs/choo#709]
expired on 3rd Aug.
there is no auto-renew?

![choo ssl-cert expired](https://user-images.githubusercontent.com/59403389/91322232-cc440100-e7bf-11ea-8a07-21b6cbdae832.png)

**Comment by goto-bus-stop** [comment]
hmm it's not expired (the expiration date is _next_ year) but the domain association seems to be wrong.

**Comment by goto-bus-stop** [comment]
@yoshuawuyts is that something you can fix? i don't know if anyone else has access :innocent:

**Comment by yoshuawuyts** [comment]
@goto-bus-stop oh yeah good question; I looked into this briefly but was unsure what's going on. I can take a look again.

**Comment by joseliber** [comment]
@yoshuawuyts I've checked the DNS record for `choo.io`:

```text
dig choo.io

; <<>> DiG 9.16.6 <<>> choo.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51356
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;choo.io.			IN	A

;; ANSWER SECTION:
choo.io.		664	IN	CNAME	netlify.com.
netlify.com.		11	IN	A	18.230.52.212

;; Query time: 3 msec
;; SERVER: 192.168.50.1#53(192.168.50.1)
;; WHEN: sex set 11 17:09:18 -03 2020
;; MSG SIZE  rcvd: 77
```

Shouldn't the CNAME be pointing to something like `<somesitename>.netlify.app`? (not sure about the TLD, I've always used `.app`).

DNS configuration was the cause of similar HTTPS certificate issues for me in the past.

**Comment by nilsnh** [comment]
Hi 👋 I believe the ssl issue could be a misconfiguration in Netlify. Netlify is not correctly issuing an SSL cert for choo.io, see docs: https://docs.netlify.com/domains-https/custom-domains/#assign-a-domain-to-a-site 

Maybe contact Netlify support and ask what could be causing the ssl issue? 🙂

@yoshuawuyts

**Comment by yoshuawuyts** [comment]
https://choo.io is back online!

Apologies this took so long!
